# Generated by Django 5.1.4 on 2026-04-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=512)),
                ('source', models.CharField(max_length=32)),
                ('rank_in_source', models.IntegerField(blank=True, null=True)),
                ('reddit_score', models.IntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='processing.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.FloatField()),
                ('breakdown', models.JSONField(default=dict)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='articles.article')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='processing.pipelinerun')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='trends.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['run'], name='trends_topi_run_id_4fa51e_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('run', 'label', 'source'), name='uq_topic_run_label_source'),
        ),
        migrations.AddIndex(
            model_name='trendsnapshot',
            index=models.Index(fields=['run', '-score_total'], name='trends_tren_run_id_7b2f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='trendsnapshot',
            index=models.Index(fields=['run'], name='trends_tren_run_id_5453b4_idx'),
        ),
        migrations.AddIndex(
            model_name='trendsnapshot',
            index=models.Index(fields=['article'], name='trends_tren_article_b13763_idx'),
        ),
        migrations.AddIndex(
            model_name='trendsnapshot',
            index=models.Index(fields=['topic'], name='trends_tren_topic_i_8eee4c_idx'),
        ),
    ]
