# Generated by Django 5.1.4 on 2026-04-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized_title', models.CharField(default='', max_length=512)),
                ('meta_description', models.TextField(default='')),
                ('slug', models.CharField(db_index=True, default='', max_length=256)),
                ('keywords', models.JSONField(default=list)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('article_enrichment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_data', to='processing.articleenrichment')),
            ],
            options={
                'verbose_name': 'SEO data',
                'verbose_name_plural': 'SEO data',
            },
        ),
    ]
