# Generated by Django 5.1.4 on 2026-04-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=2048, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('domain', models.CharField(db_index=True, default='', max_length=256)),
                ('source_rss', models.CharField(default='', max_length=512)),
                ('published_raw', models.CharField(blank=True, max_length=256, null=True)),
                ('title_fingerprint', models.CharField(db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.storycluster')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='articles.article')),
                ('story_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='articles.storycluster')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('dimension', models.PositiveIntegerField(default=0)),
                ('vector', models.JSONField(default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='articles.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article'], name='articles_ar_article_1e98ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'model'), name='uq_article_embedding_article_model')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['domain'], name='articles_ar_domain_10c091_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title_fingerprint'], name='articles_ar_title_f_21e05f_idx'),
        ),
    ]
