# Generated by Django 5.1.4 on 2026-04-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(db_index=True, default='general', max_length=64),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='articles_ar_categor_d8555e_idx'),
        ),
    ]
