# Generated by Django 5.1.4 on 2026-04-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('geo', models.CharField(default='IN', max_length=16)),
                ('lang', models.CharField(default='en', max_length=16)),
                ('status', models.CharField(default='running', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='processing__id_d09d47_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='')),
                ('main_topic', models.CharField(default='', max_length=512)),
                ('why_trending', models.TextField(default='')),
                ('why_people_care', models.TextField(default='')),
                ('who_should_care', models.TextField(default='')),
                ('content_angle_ideas', models.JSONField(default=list)),
                ('model', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='articles.article')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichments', to='processing.pipelinerun')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['article'], name='processing__article_87463a_idx'), models.Index(fields=['run'], name='processing__run_id_9e3363_idx')],
            },
        ),
    ]
